package ec.edu.ug.erp.util.constantes;

public interface ITableFieldNames {

	public static final String DESCRIPCION="DESCRIPCION";
	public static final String FECHACREACION="FECHACREACION";
	public static final String FECHAMODIFICACION="FECHAMODIFICACION";
	public static final String ESTADO="ESTADO";
	public static final String TIPO="TIPO";
	public static final String CODIGO="CODIGO";	
	public static final String NATURALEZA="NATURALEZA";
	public static final String IDENTIFICACION="IDENTIFICACION";
	public static final String TIPOIDENTIFICACION="TIPOIDENTIFICACION";
	public static final String APELLIDOPATERNO="APELLIDOPATERNO";
	public static final String APELLIDOMATERNO="APELLIDOMATERNO";
	public static final String NOMBRES="NOMBRES";
	public static final String RAZONSOCIAL="RAZONSOCIAL";
	public static final String NOMBRECOMERCIAL="NOMBRECOMERCIAL";
	public static final String GENERO="GENERO";
	public static final String FECHANACIMIENTO="FECHANACIMIENTO";
	public static final String ESTADOCIVIL="ESTADOCIVIL";
	public static final String TIPOSANGRE="TIPOSANGRE";
	public static final String TELEFONO="TELEFONO";
	public static final String FAX="FAX";
	public static final String EMAIL="EMAIL";	
	public static final String PADRE_ID="PADRE_ID";
	public static final String NIVEL="NIVEL";
	public static final String PERSONA_ID="PERSONA_ID";	
	public static final String RUTALOGO="RUTALOGO";
	public static final String URL="URL";	
	public static final String EMPRESA_ID="EMPRESA_ID";
	public static final String REGION_ID="REGION_ID";
	public static final String CIUDAD_ID="CIUDAD_ID";	
	public static final String DIRECCION="DIRECCION";
	public static final String MONEDA_ID="MONEDA_ID";	
	public static final String PAIS_ID="PAIS_ID";
	public static final String PORCENTAJE="PORCENTAJE";	
	public static final String SIMBOLO="SIMBOLO";
	public static final String LOCAL="LOCAL";	
	public static final String ESCLIENTE="ESCLIENTE";	
	public static final String ESPROVEEDOR="ESPROVEEDOR";
	public static final String ESEMPLEADO="ESEMPLEADO";	
	public static final String ACCIONLISTAR="ACCIONLISTAR";	
	public static final String ACCIONCREAR="ACCIONCREAR";
	public static final String ACCIONEDITAR="ACCIONEDITAR";	
	public static final String ICONO="ICONO";	
	public static final String ORDEN="ORDEN";
	public static final String PARAMETROS="PARAMETROS";	
	public static final String MODULO_ID="MODULO_ID";
	public static final String CREAR="CREAR";
	public static final String EDITAR="EDITAR";
	public static final String PROCESAR="PROCESAR";
	public static final String GENERAR="GENERAR";
	public static final String LISTAR="LISTAR";
	public static final String VER="VER";
	public static final String DUPLICAR="DUPLICAR";
	public static final String ENVIAR="ENVIAR";
	public static final String RECUPERAR="RECUPERAR";
	public static final String REVERSAR="REVERSAR";
	public static final String ELIMINAR="ELIMINAR";
	public static final String ANULAR="ANULAR";
	public static final String AUTORIZAR="AUTORIZAR";
	public static final String RECHAZAR="RECHAZAR";
	public static final String IMPRIMIR="IMPRIMIR";
	public static final String REPORTAR="REPORTAR";
	public static final String ACCIONGENERICA="ACCIONGENERICA";	
	public static final String TAREA_ID="TAREA_ID";
	public static final String ROL_ID="ROL_ID";	
	public static final String EMPRESAPERSONA_ID="EMPRESAPERSONA_ID";
	public static final String CLAVE="CLAVE";	
	public static final String USUARIO_ID="USUARIO_ID";
	public static final String SUCURSAL_ID="SUCURSAL_ID";
	public static final String PREDETERMINADO="PREDETERMINADO";
	public static final String MANAGEDBEAN="MANAGEDBEAN";
	
	
}
